# Generated by Django 5.2.4 on 2025-07-14 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jackets',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jackets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pants',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shirts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shirts', to=settings.AUTH_USER_MODEL),
        ),
    ]
